name: Notify Main Repo

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger orchestrator repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.MAIN_REPO_TOKEN }}" \
            https://api.github.com/repos/sparesparrow/mcp-prompts/dispatches \
            -d '{"event_type":"subrepo-updated","client_payload":{"repo":"${{ github.repository }}"}}' 