name: Notify Meta-Repo via repository_dispatch

on:
  release:
    types: [published]

jobs:
  notify-meta-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository_dispatch event to meta-repo
        env:
          META_REPO: ${{ secrets.META_REPO }}
          META_REPO_TOKEN: ${{ secrets.META_REPO_TOKEN }}
          EVENT_TYPE: mcp-prompts-updated
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $META_REPO_TOKEN" \
            https://api.github.com/repos/$META_REPO/dispatches \
            -d '{"event_type": "'$EVENT_TYPE'", "client_payload": {"source_repo": "${{ github.repository }}", "release_tag": "${{ github.ref_name }}"}}' 